name: CI

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      version:
        description: Node.js branch or tag name
        required: true
        default: v24.2.0
      arch:
        description: Target architecture
        required: true
        default: x64
        type: choice
        options:
          - x64
          - arm64
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 17 * * *'

permissions: write-all

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set Node.js branch or tag name
        run: |
          if [ "${{ github.event_name }}" = "release" ]; then
            echo "VERSION=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
            echo "ARCH=x64" >> $GITHUB_ENV
          elif [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "VERSION=${{ inputs.version }}" >> $GITHUB_ENV
            echo "ARCH=${{ inputs.arch }}" >> $GITHUB_ENV
          else
            echo "VERSION=main" >> $GITHUB_ENV
            echo "ARCH=x64" >> $GITHUB_ENV
          fi
      - name: Install tools
        run: sudo apt update && sudo apt install -y build-essential unzip jq
      - name: Build
        run: ./build.sh ${{ env.VERSION }} ${{ env.ARCH }}
      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: node-${{ env.VERSION }}-openharmony-${{ env.ARCH }}
          path: node-${{ env.VERSION }}-openharmony-${{ env.ARCH }}.tar.gz
          retention-days: 7
      - name: Upload release asset
        uses: softprops/action-gh-release@v3
        if: github.event_name == 'release'
        with:
          files: node-${{ env.VERSION }}-openharmony-${{ env.ARCH }}.tar.gz
